version: '3'

services:
  pokefront:
    build: ./frontend-pokemon-app
    container_name: pokefront
    ports:
      - "3000:3000"
    depends_on:
      - pokeback
    networks:
      - poke

  pokeback:
    build: ./backend-pokemon-app
    container_name: pokeback
    ports:
      - "8000:8000"
    networks:
      - poke

networks:
  poke:
   driver: bridge
